name: Deploy Terraform en LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Iniciar LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -no-color

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false

      - name: Verificar despliegue
        run: awslocal s3 ls
