name: Deploy Terraform en LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Iniciar LocalStack con Docker
        run: |
          docker run -d --name localstack-main \
            -p 4566:4566 \
            -e SERVICES=s3 \
            -e DEBUG=1 \
            localstack/localstack:3.0

      - name: Esperar a que LocalStack esté listo
        run: |
          for i in {1..30}; do
            if docker logs localstack-main 2>&1 | grep -q "Ready."; then
              echo "LocalStack listo"
              exit 0
            fi
            sleep 2
          done
          echo "LocalStack no arrancó correctamente"
          docker logs localstack-main
          exit 1

      - name: Comprobar LocalStack antes de Terraform
        run: |
          docker ps
          curl -s http://127.0.0.1:4566/_localstack/health

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -no-color

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false -no-color

      - name: Instalar AWS CLI
        run: pip install awscli

      - name: Verificar despliegue
        run: aws --endpoint-url=http://127.0.0.1:4566 s3 ls

      - name: Mostrar logs de LocalStack si falla
        if: failure()
        run: docker logs localstack-main
